# Generated by Django 6.0.3 on 2026-03-11 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('project_type', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('INTERNAL', 'Internal / Pet Project'), ('ADMINISTRATIVE', 'Administrative time like sick leave vacation or traveling')], default='COMMERCIAL', max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Task Title')),
                ('budget_hours', models.PositiveIntegerField(help_text='Allocated budget in hours')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='NOT_SUBMITTED', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='work_time_reporter.project')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField(blank=True, help_text='What was done?')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='work_time_reporter.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
