# Generated by Django 6.0.3 on 2026-03-12 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_time_reporter', '0002_project_manager_project_members_task_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timelog',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='work_time_reporter.weeklytimesheet'),
        ),
        migrations.AddConstraint(
            model_name='timelog',
            constraint=models.UniqueConstraint(fields=('user', 'task', 'date'), name='unique_user_task_date'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklytimesheet',
            unique_together={('user', 'year', 'week_number')},
        ),
    ]
