# Generated by Django 6.0.3 on 2026-06-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_time_reporter', '0003_weeklytimesheet_timelog_timesheet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('day_type', models.CharField(choices=[('HOLIDAY', 'Holiday / Non-working day'), ('SHORT_DAY', 'Short Day (7 hours)'), ('FREE_MONDAY', 'Free Monday when state holiday is on weekends')], max_length=20, verbose_name='Type of Day')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description (e.g., Christmas)')),
            ],
            options={
                'verbose_name': 'Company Calendar Day',
                'verbose_name_plural': 'Company Calendar',
                'ordering': ['date'],
            },
        ),
    ]
