# Generated by Django 6.0.3 on 2026-08-28 14:16

import work_time_reporter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_time_reporter', '0004_companycalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.IntegerField(default=work_time_reporter.models.current_year),
        ),
    ]
