# Generated by Django 6.0.3 on 2026-09-13 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_time_reporter', '0005_alter_project_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companycalendar',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='companycalendar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='weeklytimesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='weeklytimesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='weeklytimesheet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='weeklytimesheet',
            name='rejection_comment',
            field=models.TextField(blank=True, default='', verbose_name='Rejection Comment'),
        ),
        migrations.AddField(
            model_name='weeklytimesheet',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted At'),
        ),
        migrations.AddField(
            model_name='weeklytimesheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
