# Generated by Django 6.0.3 on 2026-09-13 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_time_reporter', '0007_backfill_timelog_timesheets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='work_time_reporter.weeklytimesheet', verbose_name='Weekly Timesheet'),
        ),
    ]
