# Generated by Django 6.0.3 on 2026-03-23 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('MAPPING', 'Needs Project Mapping'), ('PENDING', 'Pending Manager Approval'), ('APPROVED', 'Approved & Processed'), ('REJECTED', 'Rejected')], default='MAPPING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StagingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ms_project_name', models.CharField(max_length=255)),
                ('ms_task_name', models.CharField(max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_logs', to='msproject_import.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='StagingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial'), ('INTERNAL', 'Internal (Non-Commercial)'), ('ADMINISTRATIVE', 'Administrative')], max_length=20, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_projects', to='msproject_import.importbatch')),
            ],
        ),
    ]
